"""add drug_interactions table and override_reason columns

Revision ID: 75a7c785008b
Revises: f7a674ec8897
Create Date: 2026-08-18 23:42:13.967098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75a7c785008b'
down_revision: Union[str, None] = 'f7a674ec8897'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drug_interactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('drug_a', sa.String(length=255), nullable=False),
    sa.Column('drug_b', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.Enum('minor', 'moderate', 'major', name='interactionseverity'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drug_interactions_drug_a'), 'drug_interactions', ['drug_a'], unique=False)
    op.create_index(op.f('ix_drug_interactions_drug_b'), 'drug_interactions', ['drug_b'], unique=False)
    op.add_column('audit_logs', sa.Column('override_reason', sa.Text(), nullable=True))
    op.add_column('medications', sa.Column('override_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medications', 'override_reason')
    op.drop_column('audit_logs', 'override_reason')
    op.drop_index(op.f('ix_drug_interactions_drug_b'), table_name='drug_interactions')
    op.drop_index(op.f('ix_drug_interactions_drug_a'), table_name='drug_interactions')
    op.drop_table('drug_interactions')
    # ### end Alembic commands ###
