"""add drug_name and override_reason to records

Revision ID: 9b9bd59105d7
Revises: d6e08c880ceb
Create Date: 2026-08-19 11:23:46.289714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b9bd59105d7'
down_revision: Union[str, None] = 'd6e08c880ceb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('drug_name', sa.String(length=255), nullable=True))
    op.add_column('records', sa.Column('override_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('records', 'override_reason')
    op.drop_column('records', 'drug_name')
    # ### end Alembic commands ###
