"""add body_region to conditions

Revision ID: d6e08c880ceb
Revises: 75a7c785008b
Create Date: 2026-08-19 09:50:53.696703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6e08c880ceb'
down_revision: Union[str, None] = '75a7c785008b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conditions', sa.Column('body_region', sa.Enum('head', 'chest', 'abdomen', 'pelvis', 'left_arm', 'right_arm', 'left_leg', 'right_leg', 'back', 'general', name='bodyregion'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conditions', 'body_region')
    # ### end Alembic commands ###
